apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy1
  name: service1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy1
  type: nodePort
status:
  loadBalancer: {}
